theme: jekyll-theme-minimal 
title: [Стек технологий для 1С]
description: [Стек технологий, которые могут быть полезны разработчику на 1С и около 1С. По каждой технологии постарался объяснить, зачем она нужна и с чего начать изучение, если заинтересует]